name: Style Scissors
favicon: null
layout_spectrum: 0.8106331608723849
typography_spectrum: 0.6134168042335659
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9448885882738978
  lightness: 0.05926522379741073
  saturation: 0.2153030012268573
  rhythmicContrast: 0.22108538821339607
purpose: []
